//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GUI.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GUI.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oznaka Smera.
        /// </summary>
        public static string Abbrebavation {
            get {
                return ResourceManager.GetString("Abbrebavation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informacije.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodaj.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodaj Profesora.
        /// </summary>
        public static string AddProfessor {
            get {
                return ResourceManager.GetString("AddProfessor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodaj Profesora Na Predmet.
        /// </summary>
        public static string AddProfessorToSubject {
            get {
                return ResourceManager.GetString("AddProfessorToSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adresa.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id Adrese.
        /// </summary>
        public static string AddressId {
            get {
                return ResourceManager.GetString("AddressId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodaj Studenta.
        /// </summary>
        public static string AddStudent {
            get {
                return ResourceManager.GetString("AddStudent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodaj Predmet.
        /// </summary>
        public static string AddSubject {
            get {
                return ResourceManager.GetString("AddSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodaj Predmet Studentu.
        /// </summary>
        public static string AddSubjectToStudent {
            get {
                return ResourceManager.GetString("AddSubjectToStudent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prosek.
        /// </summary>
        public static string Average {
            get {
                return ResourceManager.GetString("Average", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odustani.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grad.
        /// </summary>
        public static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zatvori.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sifra Katedre.
        /// </summary>
        public static string Code {
            get {
                return ResourceManager.GetString("Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datum.
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datum rodjenja.
        /// </summary>
        public static string DateOfBirth {
            get {
                return ResourceManager.GetString("DateOfBirth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datum Ispita.
        /// </summary>
        public static string DateOfExam {
            get {
                return ResourceManager.GetString("DateOfExam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obrisi.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id Katedre.
        /// </summary>
        public static string DepartmentId {
            get {
                return ResourceManager.GetString("DepartmentId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ime Katedre.
        /// </summary>
        public static string DepartmentName {
            get {
                return ResourceManager.GetString("DepartmentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Katedre.
        /// </summary>
        public static string Departments {
            get {
                return ResourceManager.GetString("Departments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uredi.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Engleski.
        /// </summary>
        public static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Espb Poeni.
        /// </summary>
        public static string EspbPoints {
            get {
                return ResourceManager.GetString("EspbPoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fajl.
        /// </summary>
        public static string File {
            get {
                return ResourceManager.GetString("File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocena.
        /// </summary>
        public static string Grade {
            get {
                return ResourceManager.GetString("Grade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pomoc.
        /// </summary>
        public static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Broj Licne Karte.
        /// </summary>
        public static string ID {
            get {
                return ResourceManager.GetString("ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID Adrese.
        /// </summary>
        public static string IdAddress {
            get {
                return ResourceManager.GetString("IdAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id Indeksa.
        /// </summary>
        public static string IdIndex {
            get {
                return ResourceManager.GetString("IdIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indeks.
        /// </summary>
        public static string Index {
            get {
                return ResourceManager.GetString("Index", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informacije.
        /// </summary>
        public static string Information {
            get {
                return ResourceManager.GetString("Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lokalizacija.
        /// </summary>
        public static string Localization {
            get {
                return ResourceManager.GetString("Localization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Broj Upisa.
        /// </summary>
        public static string Mark {
            get {
                return ResourceManager.GetString("Mark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Novi.
        /// </summary>
        public static string New {
            get {
                return ResourceManager.GetString("New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Broj.
        /// </summary>
        public static string Number {
            get {
                return ResourceManager.GetString("Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Polozeni Predmeti.
        /// </summary>
        public static string Passed {
            get {
                return ResourceManager.GetString("Passed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Broj Telefona.
        /// </summary>
        public static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profesor.
        /// </summary>
        public static string Professor {
            get {
                return ResourceManager.GetString("Professor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string ProfessorEmail {
            get {
                return ResourceManager.GetString("ProfessorEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID Sefa Katedre.
        /// </summary>
        public static string ProfessorId {
            get {
                return ResourceManager.GetString("ProfessorId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ime.
        /// </summary>
        public static string ProfessorName {
            get {
                return ResourceManager.GetString("ProfessorName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profesori.
        /// </summary>
        public static string Professors {
            get {
                return ResourceManager.GetString("Professors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prezime.
        /// </summary>
        public static string ProfessorSurname {
            get {
                return ResourceManager.GetString("ProfessorSurname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sacuvaj.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Semestar.
        /// </summary>
        public static string Semestar {
            get {
                return ResourceManager.GetString("Semestar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Srpski.
        /// </summary>
        public static string Serbian {
            get {
                return ResourceManager.GetString("Serbian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stavi Sefa.
        /// </summary>
        public static string Set_Boss {
            get {
                return ResourceManager.GetString("Set Boss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prikazi Profesore.
        /// </summary>
        public static string ShowProfessors {
            get {
                return ResourceManager.GetString("ShowProfessors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prikazi predmete.
        /// </summary>
        public static string ShowSubjects {
            get {
                return ResourceManager.GetString("ShowSubjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drzava.
        /// </summary>
        public static string State {
            get {
                return ResourceManager.GetString("State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status(B ili S).
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ulica.
        /// </summary>
        public static string Street {
            get {
                return ResourceManager.GetString("Street", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID Studenta.
        /// </summary>
        public static string StudentId {
            get {
                return ResourceManager.GetString("StudentId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ime.
        /// </summary>
        public static string StudentName {
            get {
                return ResourceManager.GetString("StudentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Studenti.
        /// </summary>
        public static string Students {
            get {
                return ResourceManager.GetString("Students", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Studentska sluzba.
        /// </summary>
        public static string Studentska_sluzba {
            get {
                return ResourceManager.GetString("Studentska sluzba", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prezime.
        /// </summary>
        public static string StudentSurname {
            get {
                return ResourceManager.GetString("StudentSurname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id predmeta.
        /// </summary>
        public static string SubjectId {
            get {
                return ResourceManager.GetString("SubjectId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ime predmeta.
        /// </summary>
        public static string SubjectName {
            get {
                return ResourceManager.GetString("SubjectName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Predmet.
        /// </summary>
        public static string Subjects {
            get {
                return ResourceManager.GetString("Subjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Letnji.
        /// </summary>
        public static string Summer {
            get {
                return ResourceManager.GetString("Summer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Polazi Ispit.
        /// </summary>
        public static string TakeExam {
            get {
                return ResourceManager.GetString("TakeExam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zvanje.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nepolozeni Predmeti.
        /// </summary>
        public static string Unpassed {
            get {
                return ResourceManager.GetString("Unpassed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Azuriraj.
        /// </summary>
        public static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Azuriraj Departman.
        /// </summary>
        public static string UpdateDepartment {
            get {
                return ResourceManager.GetString("UpdateDepartment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Azuriraj Profesora.
        /// </summary>
        public static string UpdateProfessor {
            get {
                return ResourceManager.GetString("UpdateProfessor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Azuriraj Studenta.
        /// </summary>
        public static string UpdateStudent {
            get {
                return ResourceManager.GetString("UpdateStudent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Azuriraj Predmet.
        /// </summary>
        public static string UpdateSubject {
            get {
                return ResourceManager.GetString("UpdateSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zimski.
        /// </summary>
        public static string Winter {
            get {
                return ResourceManager.GetString("Winter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Godina.
        /// </summary>
        public static string Year {
            get {
                return ResourceManager.GetString("Year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Godina Upisa.
        /// </summary>
        public static string YearOfEnrollment {
            get {
                return ResourceManager.GetString("YearOfEnrollment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Godina studija.
        /// </summary>
        public static string YearOfStudy {
            get {
                return ResourceManager.GetString("YearOfStudy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Godina Staza.
        /// </summary>
        public static string YearsOfWork {
            get {
                return ResourceManager.GetString("YearsOfWork", resourceCulture);
            }
        }
    }
}
